# Generated by Django 4.2.30 on 2026-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive'), ('exchange', 'Exchange'), ('withdrawal', 'Withdrawal')], default='send', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('deleted', 'Supprimé')], default='pending', max_length=20),
        ),
    ]
