# Generated by Django 4.2.30 on 2026-07-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_transaction_type_alter_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
