# Generated by Django 4.2.30 on 2026-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
