# Generated by Django 4.2.30 on 2026-07-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client_email',
        ),
    ]
