# Generated by Django 4.2.30 on 2026-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_client_email_readd'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
        ),
    ]
