# Generated by Django 4.2.30 on 2026-07-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_country',
            field=models.ForeignKey(blank=True, db_column='destination_country_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='core.country'),
        ),
    ]
