# Generated by Django 4.2.30 on 2026-07-25 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_destination_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
            options={
                'db_table': 'logistics_clients',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Autre', max_length=60)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat_lng_source', models.CharField(choices=[('geocoded', 'Geocoded'), ('manual', 'Manual'), ('unresolved', 'Unresolved')], default='unresolved', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.client')),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
            options={
                'db_table': 'logistics_client_addresses',
                'ordering': ['-is_default', 'label'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LogisticsImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], max_length=10)),
                ('raw_rows', models.JSONField()),
                ('column_mapping', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_mapping', 'Pending Mapping'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_mapping', max_length=20)),
                ('created_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'logistics_import_batches',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Drop-off')], default='pickup', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clientaddress')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, to='core.client')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_driven', to='core.user')),
                ('transaction', models.ForeignKey(blank=True, db_column='transaction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.transaction')),
            ],
            options={
                'db_table': 'logistics_deliveries',
                'ordering': ['scheduled_at'],
                'managed': True,
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='delivery_status_sched_idx'), models.Index(fields=['driver', 'scheduled_at'], name='delivery_driver_sched_idx'), models.Index(fields=['task_type'], name='delivery_task_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.client')),
            ],
            options={
                'db_table': 'logistics_client_notes',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['client', 'created_at'], name='client_note_client_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['client'], name='client_addr_client_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='client_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_idx'),
        ),
    ]
