# Generated by Django 4.2.30 on 2026-07-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_clientaddress_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('other', 'Autre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
