# Generated by Django 4.2.30 on 2026-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delivery_address_note_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origin_country_manual_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
