# Generated by Django 4.2.30 on 2026-08-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_origin_country_manual_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'forum_messages',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['created_at'], name='forum_msg_created_idx')],
            },
        ),
    ]
