# Generated by Django 4.2.30 on 2026-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_forummessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forum_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
